# -*- coding: utf-8 -*-
"""2.student.mark.oop.math

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fC8iDxGDNh6XVxTInzY21BHe0v9BRyPY
"""

class Student:
    def __init__(self, id, name, dob):
        self.id = id
        self.name = name
        self.dob = dob


class Course:
    def __init__(self, id, name):
        self.id = id
        self.name = name


class StudentManagement:
    def __init__(self):
        self.students = {}
        self.courses = {}
        self.marks = {}

    def add_students(self):
        n = int(input("Number of students: "))

        for i in range(n):
            id = input("ID: ")
            name = input("Name: ")
            dob = input("DoB: ")

            self.students[id] = Student(id, name, dob)

    def add_courses(self):
        n = int(input("Number of courses: "))

        for i in range(n):
            id = input("Course ID: ")
            name = input("Course name: ")

            self.courses[id] = Course(id, name)

    def add_marks(self):
        course = input("Course ID: ")

        if course not in self.courses:
            print("This course doesn't exist. Please choose again!")
            return

        if course not in self.marks:
            self.marks[course] = {}

        for id in self.students:
            mark = input("Mark for " + self.students[id].name + ": ")
            self.marks[course][id] = mark

    def show_students(self):
        for id in self.students:
            student = self.students[id]
            print(student.id, student.name, student.dob)

    def show_courses(self):
        for id in self.courses:
            course = self.courses[id]
            print(course.id, course.name)

    def show_marks(self):
        while True:
            course = input("Course ID: ")

            if course not in self.courses:
                print("This course doesn't exist. Please choose again!")
                continue

            if course not in self.marks:
                print("This course hasn't been marked yet. Please choose again!")
                continue

            print("Course:", self.courses[course].name)

            for id in self.marks[course]:
                print(
                    self.students[id].name,
                    ":",
                    self.marks[course][id]
                )

            break


# Create object
system = StudentManagement()


while True:
    print("\n1. Students")
    print("2. Courses")
    print("3. Marks")
    print("4. Show students")
    print("5. Show courses")
    print("6. Show marks")
    print("0. Exit")

    choice = input("Choose: ")

    if choice == "1":
        system.add_students()

    elif choice == "2":
        system.add_courses()

    elif choice == "3":
        system.add_marks()

    elif choice == "4":
        system.show_students()

    elif choice == "5":
        system.show_courses()

    elif choice == "6":
        system.show_marks()

    elif choice == "0":
        break

    else:
        print("Invalid choice.")

class Exercises:

    # Ex 1
    def circle_area(self):
        r = float(input("Enter circle radius? "))

        area = 3.14 * r * r

        print("Circle area =", area)


    # Ex 2
    def temperature(self):
        c = float(input("Enter the temperature in Celsius? "))

        f = c * 9 / 5 + 32

        print(c, "(C) =", f, "(F)")


    # Ex 3
    def prime_number(self):
        n = int(input("Enter a number? "))

        prime = True

        if n < 2:
            prime = False
        else:
            for i in range(2, n):
                if n % i == 0:
                    prime = False
                    break

        if prime:
            print(n, "is a prime number")
        else:
            print(n, "is NOT a prime number")


    # Ex 4
    def perfect_number(self):
        n = int(input("Enter a number? "))

        found = False

        for p in range(2, n):
            p_prime = True

            for i in range(2, p):
                if p % i == 0:
                    p_prime = False
                    break

            if p_prime:
                m = 2 ** p - 1
                m_prime = True

                for i in range(2, m):
                    if m % i == 0:
                        m_prime = False
                        break

                if m_prime and 2 ** (p - 1) * m == n:
                    found = True
                    break

        if found:
            print(n, "is a perfect number")
        else:
            print(n, "is NOT a perfect number")


    # Ex 5
    def favorite_color(self):
        colors = ["Blue", "Yellow", "Red", "Black"]

        color = input("What is your favorite color? ")

        if color in colors:
            index = colors.index(color) + 1
            print("Your color is at index", index, "in my list")
        else:
            print("Sorry, I could not find your color")


    # Ex 6
    def ranges(self):
        range1 = range(0, 7)
        range2 = range(1, 11, 3)
        range3 = range(5, 0, -1)
        range4 = range(6, -3, -2)

        print(list(range1))
        print(list(range2))
        print(list(range3))
        print(list(range4))


    # Ex 7
    def remove_dollar(self):
        s = input("Enter a string: ")

        print(s.replace("$", ""))


    # Ex 9
    def even_numbers(self):
        numbers = [0, 34, 23, 100, 999]

        result = []

        for x in numbers:
            if x % 2 == 0:
                result.append(x)

        print(result)


    # Ex 10
    def factorial(self):
        n = int(input("Enter a number: "))

        result = 1

        for i in range(1, n + 1):
            result = result * i

        print(result)


    # Ex 11
    def divisors(self):
        n = int(input("Enter a number: "))

        result = []

        for i in range(1, n + 1):
            if n % i == 0:
                result.append(i)

        print(result)


    # Ex 12
    def distance(self):
        x1, y1, x2, y2 = map(float, input().split())

        result = ((x2 - x1) ** 2 + (y2 - y1) ** 2) ** 0.5

        print(result)


# Create object
ex = Exercises()

ex.circle_area()
ex.temperature()
ex.prime_number()
ex.perfect_number()
ex.favorite_color()
ex.ranges()
ex.remove_dollar()
ex.even_numbers()
ex.factorial()
ex.divisors()
ex.distance()