# -*- coding: utf-8 -*-
"""Labwork1B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGwxhPzOmBRH7jGiclVJdQvZ0KyjnDLT
"""
students = {}
courses = {}
marks = {}


def add_students():
    n = int(input("Number of students: "))

    for i in range(n):
        id = input("ID: ")
        name = input("Name: ")
        dob = input("DoB: ")

        students[id] = [name, dob]


def add_courses():
    n = int(input("Number of courses: "))

    for i in range(n):
        id = input("Course ID: ")
        name = input("Course name: ")

        courses[id] = name


def add_marks():
    course = input("Course ID: ")

    marks[course] = {}

    for id in students:
        mark = input("Mark for " + students[id][0] + ": ")
        marks[course][id] = mark


def show_students():
    for id in students:
        print(id, students[id][0], students[id][1])


def show_courses():
    for id in courses:
        print(id, courses[id])


def show_marks():
    course = input("Course ID: ")

    print("Course:", courses[course])

    for id in marks[course]:
        print(students[id][0], ":", marks[course][id])


while True:
    print("\n1. Students")
    print("2. Courses")
    print("3. Marks")
    print("4. Show students")
    print("5. Show courses")
    print("6. Show marks")
    print("0. Exit")

    choice = input("Choose: ")

    if choice == "1":
        add_students()

    elif choice == "2":
        add_courses()

    elif choice == "3":
        add_marks()

    elif choice == "4":
        show_students()

    elif choice == "5":
        show_courses()

    elif choice == "6":
        show_marks()

    elif choice == "0":
        break
