# -*- coding: utf-8 -*-
"""Labwork1A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a855iN7BPujYKUoV4M3o73u6XzBhNYkr
"""

#Ex 1
r = float(input("Enter circle radius? "))

area = 3.14 * r * r

print("Circle area =", area)

#Ex 2
c = float(input("Enter the temperature in Celsius? "))

f = c * 9 / 5 + 32

print(c, "(C) =", f, "(F)")

#Ex 3
n = int(input("Enter a number? "))

prime = True

if n < 2:
    prime = False
else:
    for i in range(2, n):
        if n % i == 0:
            prime = False
            break

if prime:
    print(n, "is a prime number")
else:
    print(n, "is a NOT prime number")

#Ex4
n = int(input("Enter a number? "))

found = False

for p in range(2, n)
    p_prime = True
    for i in range(2, p):
        if p % i == 0:
            p_prime = False
            break

    if p_prime:
        m = 2**p - 1
        m_prime = True
        for i in range(2, m):
            if m % i == 0:
                m_prime = False
                break

        if m_prime and 2**(p-1) * m == n:
            found = True
            break

if found:
    print(n, "is a perfect number")
else:
    print(n, "is NOT a perfect number")

#Ex 5
colors = ["Blue", "Yellow", "Red", "Black"]

color = input("What is your favorite color? ")

if color in colors:
    index = colors.index(color) + 1
    print("Your color is at index", index, "in my list")
else:
    print("Sorry, I could not find your color")

#Ex 6
range1 = range(0, 7)
range2 = range(1, 11, 3)
range3 = range(5, 0, -1)
range4 = range(6, -3, -2)

print(list(range1))
print(list(range2))
print(list(range3))
print(list(range4))

#Ex 7
def remove_dollar_sign(s):
    return s.replace("$", "")

s = input("Enter a string: ")

print(remove_dollar_sign(s))

#Ex 8
numbers = ["1","3","4","6","11","14"]
V

#Ex 9
def extract_even(l):
    result = []

    for x in l:
        if x % 2 == 0:
            result.append(x)

    return result

l = [0, 34, 23, 100, 999]

print(extract_even(l))

#Ex 10
def factorial(n):
    result = -1

    for i in range(1, n + 1):
        result = result * i

    return result

n = int(input("Enter a number: "))

print(factorial(n))

#Ex 11
def divisors(n):
    result = []

    for i in range(1, n + 1):
        if n % i == 0:
            result.append(i)

    return result

n = int(input("Enter a number: "))

print(divisors(n))

#Ex 12
x1, y1, x2, y2 = map(float, input().split())

print(((x2-x1)**2 + (y2-y1)**2)**0.5)
